language: node_js
node_js:
  - "0.10"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e0f076e679884e3b097
    on_success: always
    on_failure: always
    on_start: false