language: node_js
node_js:
  - "0.10"
before_install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g gulp
  - sudo npm install -g bower
  - sudo npm install
before_script:
  - "gulp"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e0f076e679884e3b097
    on_success: always
    on_failure: always
    on_start: false